# Generated by Django 5.0
# chat 앱 전용 모델: GenChat, GenMessage, GenUploadFile
# (Department, User, TradeFlow, Document, DocVersion, DocMessage는 documents 앱에서 관리)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),  # documents 앱의 User 모델 참조
    ]

    operations = [
        # GenChat
        migrations.CreateModel(
            name='GenChat',
            fields=[
                ('gen_chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_chats', to='documents.user')),
            ],
            options={
                'db_table': 'gen_chat',
                'ordering': ['-updated_at'],
                'managed': True,
            },
        ),
        # GenMessage
        migrations.CreateModel(
            name='GenMessage',
            fields=[
                ('gen_message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('U', 'User'), ('A', 'Assistant')], max_length=1)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gen_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.genchat')),
            ],
            options={
                'db_table': 'gen_message',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        # GenUploadFile
        migrations.CreateModel(
            name='GenUploadFile',
            fields=[
                ('gen_file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=1000)),
                ('gen_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.genmessage')),
            ],
            options={
                'db_table': 'gen_upload_file',
                'managed': True,
            },
        ),
    ]
