# Generated by Django 5.2.8 on 2025-12-04 02:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(help_text='부서명', max_length=100)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_no', models.CharField(help_text='사원번호', max_length=50, unique=True)),
                ('name', models.CharField(help_text='이름', max_length=100)),
                ('activation', models.BooleanField(default=True, help_text='활성 상태')),
                ('user_role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='사용자 역할', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('dept', models.ForeignKey(blank=True, help_text='부서', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='documents.department')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TradeFlow',
            fields=[
                ('trade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='거래 제목', max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', help_text='진행 상태', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='생성한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='trade_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_flow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('offer', 'Offer Sheet'), ('pi', 'Proforma Invoice'), ('contract', 'Sales Contract'), ('ci', 'Commercial Invoice'), ('pl', 'Packing List')], help_text='문서 유형', max_length=20)),
                ('doc_mode', models.CharField(choices=[('manual', 'Manual'), ('upload', 'Upload'), ('skip', 'Skip')], default='manual', help_text='작성 모드', max_length=20)),
                ('s3_key', models.CharField(blank=True, help_text='S3 저장 경로', max_length=500, null=True)),
                ('s3_url', models.URLField(blank=True, help_text='S3 URL', max_length=1000, null=True)),
                ('original_filename', models.CharField(blank=True, help_text='원본 파일명', max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='파일 크기 (bytes)', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME 타입', max_length=100, null=True)),
                ('upload_status', models.CharField(blank=True, choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], help_text='업로드 처리 상태', max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, help_text='에러 메시지', null=True)),
                ('qdrant_point_ids', models.JSONField(blank=True, default=list, help_text='RAG용 벡터 ID 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(help_text='거래 플로우', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.tradeflow')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='DocMessage',
            fields=[
                ('doc_message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], help_text='발신자 역할', max_length=20)),
                ('content', models.TextField(help_text='메시지 내용')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='도구 사용 결과, 검색 결과 등')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(help_text='문서', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documents.document')),
            ],
            options={
                'db_table': 'doc_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['doc', 'created_at'], name='doc_message_doc_id_bffd41_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocVersion',
            fields=[
                ('version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.JSONField(help_text='문서 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(help_text='문서', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'db_table': 'doc_version',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doc', '-created_at'], name='doc_version_doc_id_dc212c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tradeflow',
            index=models.Index(fields=['user', '-created_at'], name='trade_flow_user_id_65d277_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeflow',
            index=models.Index(fields=['status'], name='trade_flow_status_d9672d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['trade', 'doc_type'], name='document_trade_i_4418c1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_status'], name='document_upload__5cc83d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('trade', 'doc_type')},
        ),
    ]
