# Generated by Django 6.0 on 2025-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="document",
            name="extracted_text",
            field=models.TextField(
                blank=True, help_text="추출된 텍스트 (미리보기용)", null=True
            ),
        ),
    ]
