# Generated by Django 6.0 on 2025-12-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_user_managers_document_extracted_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="preview_s3_key",
            field=models.CharField(
                blank=True, help_text="미리보기 PDF S3 경로", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="preview_s3_url",
            field=models.URLField(
                blank=True, help_text="미리보기 PDF S3 URL", max_length=1000, null=True
            ),
        ),
    ]
