# Generated by Django 6.0 on 2025-12-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_preview_s3_key_document_preview_s3_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="preview_s3_key",
        ),
        migrations.RemoveField(
            model_name="document",
            name="preview_s3_url",
        ),
        migrations.AddField(
            model_name="document",
            name="converted_pdf_key",
            field=models.CharField(
                blank=True, help_text="변환된 PDF S3 Key", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="converted_pdf_url",
            field=models.URLField(
                blank=True, help_text="변환된 PDF S3 URL", max_length=1000, null=True
            ),
        ),
    ]
