# Generated by Django 6.0 on 2025-12-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_remove_document_preview_s3_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="template_data",
            field=models.TextField(
                blank=True,
                help_text="템플릿 문서에서 추출된 구조화된 데이터 (JSON)",
                null=True,
            ),
        ),
    ]
